S5 update blog admin
WildCodeSchool/orleans-0917-ateliero pull request #38
Opened 2017-11-03 16:18 UTC by charlotte45

Création de la partie Update du blog

2017-11-03 16:39 UTC, sblondeau requested changes

2017-11-03 16:39 UTC, sblondeau commented on src/Controller/ArticleBlogController.php
> +                            if ('0' == $key) {
pour quoi '0' et pas 0 ?

2017-11-03 16:39 UTC, sblondeau commented on src/Controller/ArticleBlogController.php
> +                catch (\PDOException $e) {
euh, je pense que ce try/catch n'est pas necessaire puisque vous n'en utilisez nul part ailleurs.
d'autre part, tu le fais autour d'un update d'article de blog, géré dans ton manager, je ne vois pas pourqui tu en ressort une erreur sur les dates, et ce n'est pas une \PDOException dans ce cas, ou alors ton message doit etre "erreur de modification de l'article" (sous entendu erreur de bdd), mais normalement tu devrais  vérif le format de la date AVANT l'update... bref, à revoir à mon avis

2017-11-03 16:39 UTC, sblondeau commented on src/Model/ImageManager.php
> +    public function deleteAllImageFromArticle($id)
pour toutes tes methodes delete, essaie d'envoyer un objet (selon les cas un objet Image ou Article) plutot que juste un id et type ton paramètre avec le nom de la classe

2017-11-03 16:39 UTC, sblondeau commented on src/Service/UploadManager.php
> +                    var_dump($messages);die();
attention à ne pas laisser trainer de var_dump !

2017-11-03 16:39 UTC, sblondeau commented on src/View/Admin/Blog/adminBlogUpdat.html.twig
> +                                <div class="col-sm-offset-4 col-sm-4 thumbnail">
la thunbnail doit etre appellée dans une balise figure la ligne en dessous et non dans la balise div qui indique les col.
Et la classe caption dans une balise figcaption, c'est mieux
=>Relire la doc de Bootstrap!!

2017-11-05 17:05 UTC, charlotte45 commented on src/View/Admin/Blog/adminBlogUpdat.html.twig
> +                                <div class="col-sm-offset-4 col-sm-4 thumbnail">
J'ai corrigé comme tu l'as demandé mais j'avais copié mon modèle de Bootstrap (hormis la classe thumbnail au même niveau que mes col), j'ai revérifié et dans la doc bootstrap, ils ne font pas mention des balises figure et figcaption.

2017-11-05 17:05 UTC, charlotte45 commented on src/Service/UploadManager.php
> +                    var_dump($messages);die();
Ok

2017-11-05 17:06 UTC, charlotte45 commented on src/Controller/ArticleBlogController.php
> +                            if ('0' == $key) {
Un test que j'ai fait mais j'ai oublié de retirer les quotes.

2017-11-05 17:07 UTC, charlotte45 commented on src/Controller/ArticleBlogController.php
> +                catch (\PDOException $e) {
Try et catch retirés

2017-11-05 17:39 UTC, charlotte45 commented on src/Model/ImageManager.php
> +    public function deleteAllImageFromArticle($id)
Changements effectués

2017-11-06 09:40 UTC, sblondeau approved these changes

2017-11-06 09:40 UTC, merged